### ISSUE TITLE
Can't install Redis-64 as a service

### ISSUE THREAD

**Issue by advapiIT** [microsoftarchive/redis#107]
Hello,
I've tried to install redis-64 as a service, as I did with 2.6.4 but with no success.. if I run it from console it works fine... when registering via "sc create..." it won't start.... is this a known problem?
Thanks

**Comment by jepickett** [comment]
While it would be possible to configure Redis as a service with sc, we have decided to add support for logging to the the Event Log when run as a service. In order to make this happen registry entries have to be written for both the service and the event logging infrastructure. The best solution for this installation task was to build it into Redis. 

Please see the RedisService.docx file (int bin\Release\redis-2.8.4.zip or in msvs\setups\documentation) for a more detailed description of how the --service-xxxxxxx commands work. 

You can install 2.8.4 as a service by using the --service-install flag on the Redis command line. For instance:

   redis-server --service-install redis.window.conf --loglevel verbose

You can name the service during install with the --service-name argument:

```
redis-server --service-install –service-name redisService1 –port 10001
```

There are also commands for starting/stopping and uninstalling the Redis service:
   redis-server --service-start –service-name redisService1
   redis-server --service-stop –service-name redisService1
   redis-server--service-uninstall –service-name redisService1

BTW, the Chocolatey and NuGet packages are out of date with respect to this service installation mechanism. These will be update shortly.
