### ISSUE TITLE
Redis 2.8.4 - 32 Bit support

### ISSUE THREAD

**Issue by pushkar-g** [microsoftarchive/redis#108]
Hi,
My use cased involves running Redis on low end 32 bit windows systems. I was looking at redis 2.8.4 windows port.

However 32 bit support seems to be dropped. Any specific architectural reason this support was dropped?

How easy/hard would be for us to create a patch with 32 bit support?

**Comment by jepickett** [comment]
We were having problems getting the new fork() replacement code operating reliably on 32-bit. The code has stabilized since then. I will take a look at what it would take to make this work again.

**Comment by jepickett** [comment]
I added 32-bit support in commit f441b8d0f2f0c83fdef2874355385bc515c37734. 

The fork() simulation code requires a contiguous allocation out of virtual memory for the heap. Because the address space is so constrained in 32-bit, and is also used by DLLs and other system uses, maxheap defaults to 512MB in the 32-bit build. Since I have not tested this extensively it may fail in your environment. If it does, let me know about this and I will further reduce the default maxheap setting.

I am seeing a 30% reduction in performance of the 32-bit version relative to the 64-bit version on a 64-bit OS. This may be due to the WoW thunking that happens with 32-bit processes on 64-bit. I have not tried running this on a 32-bit OS image.

**Comment by pushkar-g** [comment]
Thanks. We will verify and let you know.

**Comment by pushkar-g** [comment]
I ran a quick test and I don't see see any obvious issues.

Our deployment will probably include hundreds and possibly thousands nodes running on low end windows machines running Redis. Can you let me know if 2.8 branch is stable enough for such a production deployment or should we go with redis 2.6?

**Comment by jepickett** [comment]
I would go with the 2.8 branch.

**Comment by laurencee** [comment]
So is 32 bit available with 2.8 or not? It's listed as being dropped on the readme but the comment here sounds like you were able to patch in 32 bit support.

I have the same scenario with low spec 32 bit machines which I need redis on. The 30% performance drop is not significant for my case.

**Comment by jepickett** [comment]
The QFork implementation has some drawbacks in the 32-bit build that we don't anticipate being able to workaround. Therefore we have decided to not officially support it. To get the 32-bit binaries you should download the source and build it. We are not publishing the 32-bit binaries via NuGet or Chocolatey. We are also not checking in the 32-bit binaries into the source tree. The 32-bit build is not being tested, so use it at your own risk.

**Comment by laurencee** [comment]
Thanks for the reply, from my testing the 32 bit compiled from source seems to be working as expected. I'll need to run a few more tests to see if there is anything I'm using which is broken.

Do you see a 32 bit version coming back in the future sometime or is it going to be dropped entirely from all future releases?

**Comment by jepickett** [comment]
We will keep the build-it-yourself option indefinitely.I don't think we will see an official package being published.
