### ISSUE TITLE
redis-server.exe is valid but is for a machine type other than the current machine

### ISSUE THREAD

**Issue by brugnara** [microsoftarchive/redis#132]
I'm getting this error launching the BIN downlaoded from this repo, on Windows 2003R2 SP. 

```
redis-server.exe is valid but is for a machine type other than the current machine
```

Many thanks.

**Comment by jepickett** [comment]
It sounds like you are trying to run the 64-bit binaries on a 32-bit system. This will result in the error you are seeing.  The 32-bit flavor of Redis has significant limitations and is nowhere near as performant as the 64-bit version. Our goal is to provide the best experience possible with Redis on Windows.  Because of this we are not currently recommending that Redis is used on a 32-bit OS. We are also no longer providing pre-built 32-bit binaries. If you really need 32-bit support you can download the source and build your own binaries. I make sure the 32-bit target builds every time I update the binaries, but I am not running the unit test on these binaries except once in a blue moon.

**Comment by brugnara** [comment]
It's exactly what happened. I'm trying with a 2.6 version. Thank your for the hint.
