### ISSUE TITLE
dump.rdb not created

### ISSUE THREAD

**Issue by ranalsheikh** [microsoftarchive/redis#138]
I have problems with automatic backup and with BGSAVE command.  The problems seem to be related so I am creating one issue.  I am running redis 2.8.9 (64bit) on windows 7.

Problem 1: 
I configure:  save 15 1 (short period is for testing only).  Service is started as local system account.

dump.rdb is not created automatically and if I try to run 'SAVE' I get the message  "(error) ERR Background save already in progress"

Problem 2:  
I comment out all save configuration and re-install the service.

I open redis-cli, set several keys and then type 'SAVE'.  The file dump.rdb is created immediately.

When I try to run BGSAVE the process hangs for 10 seconds and then shows (Error) ERR.  After that I cannot run SAVE anymore and getting the same error message as in problem 1 above.

Any help to troubleshoot the problems is appreciated.  Thanks in advance.

**Comment by jepickett** [comment]
---

From Redis.Windows.conf:

 By default Redis will stop accepting writes if RDB snapshots are enabled
 (at least one save point) and the latest background save failed.
 This will make the user aware (in an hard way) that data is not persisting
 on disk properly, otherwise chances are that no one will notice and some
 distater will happen.

 If the background saving process will start working again Redis will
 automatically allow writes again.

 However if you have setup your proper monitoring of the Redis server
 and persistence, you may want to disable this feature so that Redis will
 continue to work as usually even if there are problems with disk, 
 permissions, and so forth. 

---

We need to identify why the background write is failing in your environment. Do the following:
1.  Grab a copy of Process Monitor (http://technet.microsoft.com/en-us/sysinternals/bb896645)
2.  Launch ProcMon.exe
3.  In the Process Monitor Filter dialog add “Process Name” “contains” “redis-server” then “include” to the list of filters:
   ![processmonitorfilterdialog](https://cloud.githubusercontent.com/assets/5193368/3464435/eea42414-024c-11e4-884e-8f42c878ebd5.png)
4.  Ensure the Filter- - >Drop Filtered Events menu item is checked
5.  Ensure the File- - >Capture Events menu item is checked
6.  Replicate your problem (lots of messages will show up in the Process Monitor window)
7.  Use the File- - >Save… menu item to save the file as a .PML file
8.  Compress the file and put it somewhere I can download it (OneDrive, DropBox, etc.), then send the instruction for accessing the file to v-jonpic@microsoft.com

**Comment by ranalsheikh** [comment]
Thank you for your response.  After spending some time troubleshooting the problem we decided to use redis cache service from amazon, so I will not continue with the windows setup.

**Comment by jepickett** [comment]
likely this is fixed in commit 88a62862d3a2e1b7e91cd157b2267e167fffa8a8.
