### ISSUE TITLE
Watcher no longer provided ?

### ISSUE THREAD

**Issue by robertcatgithub** [microsoftarchive/redis#150]
Is RedisWatcher still relevant ?

**Comment by jepickett** [comment]
RedisWatcher was not managing service startup/shutdown issues well with the new QFork infrastructure. In order to address these problems I added the code to make Redis a standalone service. Please see the RedisService.docx file that comes with the binary distributions (also in the msvs\setups\documentation folder). Is there some aspect of RedisWatcher that is not in the current service architecture that you really need?
