### ISSUE TITLE
Redis crashed with error EndForkOperation: 0x000001e7 - EndForkOperation: Remapping ForkControl block failed

### ISSUE THREAD

**Issue by glikoz** [microsoftarchive/redis#157]
We are using redis as windows Service (version is 2.8.9 (nuget version))

Only differences in our configuration file are ( to sample conf file)  :
- database 1
- maxheap 2gb

redis database size is ~250MB
free space in C is ~14GB
operating system is windows 2012 R2 

So why redis crashes?

**Comment by glikoz** [comment]
This happened second time today. Is there any service option: automatically start redis service when crashed?

**Comment by jepickett** [comment]
In the services Control Panel, find your Redis service (or services). Right click on the service, select Properties and navigate to the Recovery tab. This will give you the options for automatically restarting the service. This mechanism will allow you run a program on restart that could notify you via email of the failure. You can also trigger the computer to restart.

I have never seen this failure. You are the first to report it. Please try the latest binaries from GitHub to see if any of the changes in the last month has changed this behavior. If it still breaks, let me know, and I will work with you to capture a full process dump as close to the error location as possible so that I can understand under what run-time conditions the code is failing in.

**Comment by glikoz** [comment]
![redis_error](https://cloud.githubusercontent.com/assets/1757659/3844474/9465456e-1e49-11e4-8978-8ff077d451e5.png)

Thanks for Recovery tip.
I've sent service error detail as screenshot. (bottom message comes first and then the error message comes, in the same second)
There is another problem also: it's level is error but it seems as "Information".  It's  very hard to find new errors because all things (errors also) are saved as "Information".

I will give info about the problem. Thanks again.

Extra hint: Other problem: We could not manage to run our redis with "maxheap 1gb" configuration (db was ~250MB),  redis was crashing after ~10 seconds or after n clients.(but sorry we dont know the error message, it was 2.8.4 as console) We upgraded redis to 2.8.9 and we changed maxheap to 2gb. Maybe both problems could be related with maxheap,db-size.

Extra info: We are not using antivirus vs..

**Comment by jepickett** [comment]
We have placed the Redis heap into a memory mapped view. During fork() operations we enable the server to continue updating the heap by making copy-on-write pages. When the fork() operation is complete we unify the base memory mapped view with the COW pages and then discard these pages. In the current implementation the COW page discard operation is achieved by unmapping the memory mapped view and then remapping it. Where the failure is occurring in this case is at the remapping operation. The only thing will prevent this from working is if something else is allocating memory in the region of our heap in between the unmap and remap operations. This race condition results in not being able to remap the Redis heap, and thus I have to exit at that point. Since we are not loading DLLs at that time, I think the problem must be related to some 3rd party program that is dynamically loading DLLs into the process. 

I have a potential solution for this problem that would allow us to remove the COW pages without unmapping the view. Unfortunately this appears to only work on Win8+ and uses a semi-documented flag to do so. Because of this I have to get permission before I can check in the code. Given the slowness of the process, it may be a few weeks before I know if I can check this in.

**Comment by jepickett** [comment]
The fix has been pushed in commit 16cefcf0b5d7278b431dfe42c69b5f095cdf2b3c.Let me know if this is fixed in your environment.

**Comment by glikoz** [comment]
sorry jepicket, I was on holiday.. I will check it and than reopen or silence :)

**Comment by bdesmeules** [comment]
Hi,

We are testing the Windows version of Redis (currently using it on different Ubuntu LTS servers) on one of our test environments. The machine is running Windows Server 2012 R2 and we are using the latest release of Redis on Windows (2.8.12). This release includes the fix from jepickett.

We have experienced the exact same issue as glikoz:

[5968] 07 Oct 16:31:24.677 # fork operation complete
[5968] 07 Oct 16:31:24.858 # EndForkOperation: 0x000001e7 - EndForkOperation: Remapping ForkControl block failed.: unknown error

The dump.rdb file is ~53MB. We have not specified any maxheap or heapdir configuration directives so the service is using the default values. There is 59GB free space on the C: drive of the server.

Is there any update on this issue? Besides setting the recovery options of the Windows service, is there something else I can try to gather more information about the issue?

Thanks.
