### ISSUE TITLE
Redis Out Of Memory allocating

### ISSUE THREAD

**Issue by tthanhsang** [microsoftarchive/redis#158]
I've set maxmemory 50mb and  maxmemory-policy allkeys-lru in redis config file.

In my case, I set 69000 user with key is USER:1, USER:2,... USER:69000 and value is USER info I get from mongodb. 
It works OK with memory about 50M and allkeys-lru
When I set with key USER:all and value is all user which I get from mongodb, Redis throw "VirtualAlloc/COWAlloc fail!" 
This log
[3212] 04 Aug 14:21:22.183 # fork operation complete
[3212] 04 Aug 14:21:22.216 \* Background saving terminated with success
[3212] 04 Aug 14:21:26.965 - Accepted 2001::127:51050
[3212] 04 Aug 14:21:27.225 - DB 0: 43921 keys (0 volatile) in 65536 slots HT.
[3212] 04 Aug 14:21:27.232 - 1 clients connected (0 slaves), 51941312 bytes in use
[3212] 04 Aug 14:21:32.242 - DB 0: 43921 keys (0 volatile) in 65536 slots HT.
[3212] 04 Aug 14:21:32.252 - 1 clients connected (0 slaves), 51941312 bytes in use
[3212] 04 Aug 14:21:36.047 # Out Of Memory allocating 10484297 bytes!

When I try set large object again and redis service stop
[3212] 04 Aug 14:34:41.178 # Out Of Memory allocating 18430351 bytes!

**Comment by jepickett** [comment]
This could be either that you are trying to put too much into Redis, or that memory fragmentation is limiting how large a block you can allocate. In the Windows version of Redis we have a fixed heap size (due to the fork() simulation architecture). This defaults to be 50% larger than the maxmemory size specified. In most cases this is sufficient headroom to allow for memory fragmentation. If in your situation this is not sufficient, you can use the maxheap flag (see redis.windows.conf) along with the maxmemory flag to make the heap larger than this. 10mb is a very large block to be allocating on a 75mb heap that is likely already very fragmented.

BTW, the maxmemory flag only acts on new key creation. If, for example, you have a list that you are continually adding to, the maxmemory settings will not purge the list or refuse the write if memory usage grows above the maxmemory value. In this scenario you may easily exhaust all available memory.

**Comment by tthanhsang** [comment]
Thanks for your comment.
Can you give me advice about maxheap?
How many maxheap size appropriate with 18430351 bytes?
when I increase USER:all , should I increate maxheap?

**Comment by jepickett** [comment]
You will have to increase maxheap until you are not seeing a problem. Since you are using a maxmemory size of 50M, and we are suspecting that fragmentation is your problem, I would start with maxheap at 200M(4x maxmemory) and then increasing or decreasing this as necessary. 

I am curious about the 18MB allocation. Is this a single string, or are you growing a large array?

**Comment by tthanhsang** [comment]
Thank for your advise
I'm growing a large array
what is difference between a single string and a large array?

**Comment by jepickett** [comment]
The length of the string is passed in with the SET, so the string is allocated once. It does not fragment the heap. 

An array is allocated with an initial size. Once the array is filled up, Redis allocates a block twice as large and copies the existing data into the new array buffer. Once it fills up again this process is repeated. Generally the array buffer can not be reallocated in place. Thus you get large holes in the heap. Very quickly you can get into a situation where you can not allocate a large enough block to satisfy the memory request, not due to lack of free space, but due to lacking a large enough block to satisfy a huge memory request.

An interim solution is to make your heap larger. A better long term solution is to organize your data differently.
