### ISSUE TITLE
ULONG_MAX-(1024*64)' is not true

### ISSUE THREAD

**Issue by lmagine** [microsoftarchive/redis#170]
I received this error message during data mass inserting with replication..
used memory 40GB(rdb 23GB)

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[2472] 30 Sep 15:07:38.848 # === ASSERTION FAILED ===
[2472] 30 Sep 15:07:38.848 # ==> ..\src\networking.c:1778 'c->reply_bytes < ULONG_MAX-(1024*64)' is not true

**Comment by lmagine** [comment]
same issue : https://github.com/antirez/redis/issues/2035

**Comment by jepickett** [comment]
Which version of Redis are you using? Commit  874c21d801ad4fc43fd2f480cfc7dc50f697b49d (available in 2.8.15+) fixed a similar bug with master/slave synchronization when the RDB file was larger than 2Gig. This is a more general problem with the size of 'long' on x64 Windows because ABI differences (LP64 vs. LLP64 model). Fixing this everywhere will touch a lot of code, so I have been fixing this on a case-by-case basis. I am also working on an ABI portability layer to fix this in the general case.

**Comment by lmagine** [comment]
i'm using redis for windows 2.8.17.
So, larger than 2GB rdb file(less than 40GB) has been works well.
I think this problem seems to be 'ABI issue you talked'.

**Comment by jepickett** [comment]
I added a fix for this instance of the ABI issue in commit 47406f9591b503763290ac856e35a54a74bc053e. We are still researching a more general long term solution to the remaining ABI issues. I tested this on a 112GB VM. I filled most of the heap and had a 80+GB RDB file produced. Let me know how this works in your environment.

**Comment by jepickett** [comment]
Since I have not heard back from you in a week, I am closing this issue at this time. If it recurs just reopen the issue.

**Comment by khayong** [comment]
I also have the similar error on the latest version 2.8.19.1.

[4972] 07 Jun 10:59:31.308 # === ASSERTION FAILED ===
[4972] 07 Jun 10:59:31.308 # ==> ..\src\networking.c:1795 'c->reply_bytes < ULONG_MAX-(1024*64)' is not true

**Comment by orangemocha** [comment]
@khayong this problem is fixed in the upcoming 2.8.21 release, which should come out next week at the latest.
