### ISSUE TITLE
change deployment strategy

### ISSUE THREAD

**Issue by jakoch** [microsoftarchive/redis#172]
Hello!

When using one of the "redis-win" zip archives provided here https://github.com/MSOpenTech/redis/releases
you have to download the zip, unextract and then unextract `/bin/release/redis-{maj.min.patch}.zip` again, just to get redis. The archives contain the source and the binaries as zip, which are committed to git.

Let me suggest a change of your deployment strategy.

Please stop deploying your zipped binaries to "bin\Release" with Git commits.
Please start to upload your zipped binaries to "Github Releases" instead
This would allow fetching the latest release and it's version number from https://github.com/MSOpenTech/redis/releases/latest.

Or use Appveyor Artefacts and a deployment strategy from there:
http://www.appveyor.com/docs/deployment & http://www.appveyor.com/docs/packaging-artifacts.
You might consider "nightly builds": https://ci.appveyor.com/project/MSOpenTech-lab/redis/build/artifacts

Regards, Jens

**Comment by orangemocha** [comment]
Thanks @jakoch : suggestion accepted! Since https://github.com/MSOpenTech/redis/commit/8d5716c03ea9566749e12b33ba371e65a713cba2 the .zip file has been removed from source. Instead, we will be uploading it with each release on the releases page (https://github.com/MSOpenTech/redis/releases).
At the moment the process of creating releases is a manual one. We'll be looking into using AppVeyor in the future.

**Comment by jakoch** [comment]
:+1: Good decision & Merry Christmas.

**Comment by aharpervc** [comment]
:+1: very useful
