### ISSUE TITLE
BeginForkOperation: system error caught. error code=0x000005af

### ISSUE THREAD

**Issue by ipanocloud** [microsoftarchive/redis#177]
Hi,
Our Redis 2.8.12 installation on Windows 7 Ultimate,An error has occurred after long time running.
[1872] 09 Oct 17:28:42.882 - 12 clients connected (0 slaves), 4609456 bytes in use
[1872] 09 Oct 17:28:43.082 \* 10 changes in 300 seconds. Saving...
[1872] 09 Oct 17:28:43.083 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

[1872] 09 Oct 17:28:43.083 # Can't save in background: fork: Invalid argument
[1872] 09 Oct 17:28:43.183 \* 10 changes in 300 seconds. Saving...
[1872] 09 Oct 17:28:43.336 # fork operation complete
[1872] 09 Oct 17:28:43.620 \* Background saving terminated with success

Do you know what might be the root cause?

Thanks

**Comment by jepickett** [comment]
The 0x5af error indicates that you are out of System Paging File space. Is your paging file configured to used the windows managed size option?

**Comment by ipanocloud** [comment]
I'm sorry, but the specific how should I do?

**Comment by jepickett** [comment]
control panel --> System --> Advanced System Settings --> Select the Setings... button in the performance group box --> Select the Advanced tab --> click on the Change... button

The default configuration should be set to the "Automatically managing paging file size for all drives", Other settings may not offer enough paging file space to satisfy Redis.

**Comment by jepickett** [comment]
Has changing the paging file settings fixed your issue?

**Comment by ipanocloud** [comment]
Is testing, remains to be seen

**Comment by ipanocloud** [comment]
If I have 4 TB of disk space, what should I paging file size set

**Comment by jepickett** [comment]
That is not the right question to be asking. You should be asking something long the lines of: How much disk space do I need for the data I am storing in Redis? For a given amount of data stored in Redis you will have to have a heap sized sufficiently to store that data (call that X). In sizing the heap you will have to allow for some amount of memory fragmentation to occur. 50% is a reasonable amount of fragmentation allowance (1.5X). Because we map the heap into a memory mapped file, you will have to have that available on disk at the moment you launch Redis. During forking operations, potentially 3 times the size of the heap will be allocated from the system paging file (though this is typically much closer to to size of the heap). The forking operations will produce temporary AOF and RDB files that will eventually replace existing AOF and RDB files. So you should have enough disk space to accommodate 1.5X + 3(1.5X) + 2X = 8X in the worst case scenario. An 8GB heap should have at least 64GB free disk space available before launching Redis.

**Comment by jepickett** [comment]
Have you had sufficient time to verify that changing the paging file settings has resolved your issue?

**Comment by jepickett** [comment]
Closing due to lack of additional discussion.
