### ISSUE TITLE
can't start redis-server over "not enough contiguous memory available". With 24GB of memory.

### ISSUE THREAD

**Issue by Pomax** [microsoftarchive/redis#183]
I'm trying to run redis-server and am getting the following error:

```
C:\Users\Mike\Documents\Git projects\temp>redis-server
[9328] 20 Oct 11:12:02.329 #
The Windows version of Redis allocates a memory mapped heap for sharing with
the forked process used for persistence operations. In order to share this
memory, Windows allocates from the system paging file a portion equal to the
size of the Redis heap. At this time there is insufficient contiguous free
space available in the system paging file for this operation (Windows error
0x5AF). To work around this you may either increase the size of the system
paging file, or decrease the size of the Redis heap with the --maxheap flag.
Sometimes a reboot will defragment the system paging file sufficiently for
this operation to complete successfully.

Please see the documentation included with the binary distributions for more
details on the --maxheap flag.

Redis can not continue. Exiting.
```

This is a machine with 24GB of memory, of which 18.8 is available when I try to run redis-server, so it really shouldn't be possible for it to report there's not enough memory free to create the necessary memory map.

**Comment by nmehlei** [comment]
you need more hard disk space, at least as much as you have memory.
Or, like the text says, you have to specify the --maxheap argument.
This is related to the way MSOpenTech rebuilt the fork mechanism that is used on unix based systems

**Comment by jepickett** [comment]
What OS flavor are you using? Are you using a custom system paging file size, or have you disabled the page file completely?

**Comment by Pomax** [comment]
64 bit Windows 7, 24GB ram, no fancy system paging settings other than having the pagefile located on an SSD (for fast paging) with 58GB free. If I set the maxheap to 2gb in the conf, it'll run just fine, so it might just be trying to allocate an unreasonably large contiguous chunk.

Reading the conf docs, the function used sounds reasonable for low memory machines (1 or 2 GB, yielding a 3 or 8GB mapping) but on systems with plenty of ram Redis will be trying to allocate _insanely huge_ memory maps. I have 24GB ram in this machine, so if I follow the function given, Redis is going to try to set up an almost 75GB memory map. If that's true, then I guess it makes sense that windows cuts that attempt off. There's not enough disk space to accommodate that.

Defaulting it to "either function-based size or just a flat 8GB if the function would yield more than 8GB" might make more sense than to follow the mem+2*maxheap formula no matter how much memory is installed.

**Comment by jepickett** [comment]
Redis is intended to be an in memory database. Making the most out of the physical memory available is consistent with that goal. Given what we have to do to make fork() work on Windows, we unfortunately have a disk allocation requirement that is not present with the Posix version of Redis. Disk space is inexpensive relative to RAM, so it is a reasonable tradeoff for most situations.

The page file allocation happens when we map the view of the heap into the parent process, and again for each copy-on-write page added to the memory mapped view during the forking process. Maximum theoretical page file commit is thus three times the size of the heap (heap + parent COW pages + child COW pages). Actual usage is substantially less than this since you are unlikely to be able to touch every page in the parent process during a fork() operation, and COW page creation in the child process is minimal.

The error being reported indicates that you can not map a contiguous 24GB block in the paging file. The paging file is shared with all the applications on the machine. It is possible that you have enough running on your machine that a 24GB swap file allocation will not be possible. There is no good way to determine what the maximum page file size could be since that potentially varies at run time. Many development machines are so loaded with other expensive processes that the defaults will cause Redis to fail on startup, and production deployment scenarios vary so widely that it is impossible to find a default heap size that will satisfy everyone. The recommended production configuration of Redis is on an essentially virgin OS. The defaults we have chosen should work with 24GB of physical RAM in that scenario. 

While avoiding error messages is a good thing, eliminating error messages altogether is not. Is the error message being presented sufficiently clear to point you in the right direction for configuring Redis on your machine?

**Comment by jepickett** [comment]
I tested installing Redis on a virgin Server 2012 R2 VM with 112GB of RAM. With sufficient disk space available for the heap file on the installation drive, Redis launches without any command line arguments. A 112GB heap file is produced on launch, but this is expected and documented behavior.
