### ISSUE TITLE
redis-server.exe --test-memory spend more than 6 hours

### ISSUE THREAD

**Issue by ScottKaiGu** [microsoftarchive/redis#268]
the cmd is:
_redis-server.exe --test-memory 1024_

i've spend more than 6 hours...in my console, it says: *random fill [33] *...

my redis:
_Redis 2.8.21 (00000000/0) 64 bit, stand alone mode, port 6379_

server info:
![2015-07-15 18_25_33-mremote _ confcons may4 2015 xml](https://cloud.githubusercontent.com/assets/4525469/8696456/1241be9e-2b1f-11e5-9c31-c76a2cb6bc9c.png)
![2015-07-15 18_25_02-mremote _ confcons may4 2015 xml](https://cloud.githubusercontent.com/assets/4525469/8696455/123dd5fe-2b1f-11e5-8ddf-b88c1ebc1a05.png)

**Comment by enricogior** [comment]
Hi @ScottKaiGu,
"random fill [33]" means that the test has already looped 32 times and it's currently executing the 33rd loop.
The test has an hard-coded value of 50 for the total number of loops to run. That was in the original code (written for Linux). In our port to Windows we didn't change it, but it looks like it may be an excessive value. We should at least allow to overwrite it by the user.
Thank you for your feedback.

**Comment by enricogior** [comment]
@ScottKaiGu,
today we released 2.8.2101 with additional Windows-specific bug fixes, the issue you reported made it to the release, so now the memory test only loops 5 times instead of 50.
The new Redis on Windows release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101)
Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey  packages.
