### ISSUE TITLE
pdb files included in the MSI

### ISSUE THREAD

**Issue by baywet** [microsoftarchive/redis#287]
Hi,
My team and I noticed that pdb files are included in the MSI. To our understanding MSI is meant for production and should not come with pdb's.
Could it be excluded from the package? If you still want to provide people the ability to debug it maybe you could create another msi called debug symbols for redis?
Thanks!
![redis](https://cloud.githubusercontent.com/assets/7905502/9044005/90c85e04-39e7-11e5-8db2-757880524b4b.png)

**Comment by enricogior** [comment]
Hi @baywet,
I'm not sure I understand what is the problem you are having with the pdb files.
The pdb files were added to the MSI not "to provide people the ability to debug", but in order to provide a full bug report when Redis crashes.
It's the same functionality that Redis has on Linux and that was missing on Windows.
Since we added the pdb files to the official releases we received great feedback that helped addressing several issues that would have not been fixed otherwise.
People that want to debug will use a full debug build that they can create themselves from the source code.
The pdb files don't cause any harm in production, therefore at this point we don't have any plan to remove the pdb files or to create a separate MSI.
But if you want you can delete them or build your own MSI that doesn't include them.
I hope I answered your question, if not let me know.
Thanks.

**Comment by baywet** [comment]
Hi @enricogior ,
Thanks for taking the time to answer me. I understand that pdb files are really useful when you are in a debug/troubleshooting situation.
But, from my point of view, it should not be systematically installed, it causes the installation to take more space and makes the footprint of redis bigger.
When you install windows for example, it doesn't come with debugging symbols. This is why you have a separate installer on MSDN "debug symbols for windows".
This is why I don't think pdb should not be included in production installations but deployed only if needed (and retracted when done). It's kind of the same reason why you don't install let's say visual studio on a production environment. Sure it should not cause any harm but it will increase the image size, require more maintenance and so on...
That being said, if most of the community likes it like that, I perfectly understand and we'll find solutions on our end.
Thanks!

**Comment by enricogior** [comment]
@baywet 
Redis and Redis on Windows are not products sold by a company, they are the result of the effort of some individuals + the help of the community.
There is no way to improve Redis on Windows without the help of the users that run the binaries on their machine and report the issues.
Without the pdb installed by default it would be nearly impossible to improve the quality of the code.
Building your own MSI is not that complicated:
- first build the Redis binaries using the msvs/RedisServer.sln solution
- then open the MSI solution msvs/msi/RedisMsi.sln
- edit Product.wxs to remove <ComponentGroupRef Id="SymbolsComponents" />
- build the MSI solution

That will do it ;)

**Comment by baywet** [comment]
@enricogior sure, I perfectly understand and it makes sense given the fact that redis for windows it built by a community. If the community chose to keep pdb's then don't change it just for us :)
And yes we'll probably do that, we might automate that part with our release pipeline.
Thanks for your time.

**Comment by enricogior** [comment]
@baywet 
you're welcome :)
