### ISSUE TITLE
Diskless and QFork file creation

### ISSUE THREAD

**Issue by satish860** [microsoftarchive/redis#364]
Hi All,
Every time when the redis starts there Qfork file gets created and it is occupying the 16 GB (Ram Size) . Can we avoid it by turning on the Diskless in the config.

**Comment by enricogior** [comment]
Hi @satish860 
in Redis on Windows v2.8.x the QFork file is used to simulate the Linux fork() command that in turn is used when persisting data to disk and when executing the diskless replication.

If persistence and replication are not required, the Windows-specific 'persistence-available' flag can be set to 'no' in order to avoid the QFork file creation, but with the persistence disabled, no replication can be done. Diskless replication on Windows is not a pure in-memory replication since the way it has been implemented on Linux still requires a fork() call that on Windows requires the QFork file to back the copy-on-write mechanism, therefore without the QFork file the diskless replication is not possible.

In v3.0.x we have changed the copy-on-write mechanism and we don't use the QFork file anymore, therefore if you need a less disk-hungry implementation you may consider [v3.0 RC1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc1).
Thank you.

**Comment by enricogior** [comment]
@satish860 
closing the issue.
Please feel free to reopen it if needed.
Thank you.
