### ISSUE TITLE
Upgrade project files to VS 2012

### ISSUE THREAD

**Issue by pinscript** [microsoftarchive/redis#37]
Hi,

What do you guys say about upgrading the project files to support VS 2012? When one tries to open the solution in VS 2012 the following message appears:
`
Error   2
error MSB8020: The builds tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found.
To build using the v100 build tools, either click the Project menu or right-click the solution,
and then select "Update VC++ Projects...". Install Visual Studio 2010 to build using the
Visual Studio 2010 build tools.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets
`
It's easliy solved by setting `<PlatformToolset>v110</PlatformToolset>` in each project file. I could of course install VS 2010 but if we could upgrade to 2012 that would be perfect. I could not find any bugs when doing this.

**Comment by clca** [comment]
Makes sense, we will include updated (VS2012) solution files with the next commit.

**Comment by itsnotvalid** [comment]
Since VS2012 is not working on WinXP VS2010 may still be a better target.

**Comment by ejbrennan99** [comment]
> > Since VS2012 is not working on WinXP VS2010 may still be a better target.

On the otherhand, since windows xp is now almost 13 years old, if you have to decide I much rather see Vs2012 solutions files, and no xp support than the other way around.

**Comment by matthiasg** [comment]
it is possible to upgrade sln files from vs2010 to vs2012. it is NOT possible to easily downgrade.

also: xp may be old, but the VC Runtime distributed with vs2010 is available on many machines. the vs2012 runtime is not (AFAIK)

From: E.J. Brennan
Sent: ‎Tuesday‎, ‎April‎ ‎30‎, ‎2013 ‎3‎:‎06‎ ‎PM
To: MSOpenTech/redis

Since VS2012 is not working on WinXP VS2010 may still be a better target.

On the otherhand, since windows xp is now almost 13 years old, if you have to decide I much rather see Vs2012 solutions files, and no xp support than the other way around.

**Comment by miranda-zhang** [comment]
![image](https://f.cloud.github.com/assets/1501851/552993/0fad233c-c373-11e2-9b35-54762027eabc.png)
i'm a newbie in this, just try to move the dev environment to a new win8 machine, i have tried to update the VC++ project, but it still says it's incompatible..

**Comment by djey47** [comment]
Hello. I did achieve to build latest version from source (Windows 7 x64, Visual Studio 2012 Express). Projects were loaded succesfully, compiling without errors.

VS2012 does exist in many versions, please check yours - it should not be the version dedicated to Windows RT apps (aka metro apps in the past) ;)

**Comment by miranda-zhang** [comment]
The version I'm using seems right to me:
Microsoft Visual Studio Express 2012 for Windows 8
Version 11.0.50727.1 RTMREL
Microsoft .NET Framework
Version 4.5.50709

There is nothing in the ERROR list, but OUTPUT says:

Project 'RedisServer' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
C:\Users\Miranda\Downloads\redis-2.6\redis-2.6\msvs\RedisServer.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'RedisBenchmark' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
C:\Users\Miranda\Downloads\redis-2.6\redis-2.6\msvs\RedisBenchmark\RedisBenchmark.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'RedisCheckAof' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
C:\Users\Miranda\Downloads\redis-2.6\redis-2.6\msvs\RedisCheckAof\RedisCheckAof.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'RedisCheckDump' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
C:\Users\Miranda\Downloads\redis-2.6\redis-2.6\msvs\RedisCheckDump\RedisCheckDump.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'RedisCli' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
C:\Users\Miranda\Downloads\redis-2.6\redis-2.6\msvs\RedisCli\RedisCli.vcxproj : error  : Exception from HRESULT: 0x80042003

**Comment by djey47** [comment]
Download and  install VS2012 Express Desktop Edition instead. Should work on Windows 8.
VS2012 'Windows 8' edition targets non-native (RT) applications.

Yeah I know, product name is rather confusing ...

**Comment by miranda-zhang** [comment]
djey47, you rock ,  Desktop Edition works like a charm.

**Comment by BeatriceOltean** [comment]
Feature complete and available in the 2.6.14.
