### ISSUE TITLE
Memory Usage reporting not correct

### ISSUE THREAD

**Issue by SebastianStehle** [microsoftarchive/redis#378]
We made an upgrade from redis 2.8 to 3.0.500

In the past our redis server consumed about 1-2gb of RAM, so we defined a maxmemory of 4gb. I ensured with "config get maxmemory" that anything is configured correctly. The process explorer shows, that at the moment (at night in germany) the server consumes about 500mb. But a lot of queries fail "cannot execute command because memory > maxmemory'.

When I run "info" I get the following results
# Memory

used_memory:4572985896
used_memory_human:4.26G
used_memory_rss:4573017120
used_memory_peak:4573165960
used_memory_peak_human:4.26G
used_memory_lua:315392
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

So there might be something going wrong here.

My full config:

include redis.windows.conf
logfile "D:\Redis\host\redis.master.log"
port 6379
maxmemory 8gb
dir D:\Redis\host

Redis is running on a windows server with 64GB RAM, 30+ GB free.

**Comment by enricogior** [comment]
Hi @SebastianStehle
can you please run the "config get maxmemory" command from redis-cli to verify the current maxmemory value? 
Thank you.

**Comment by SebastianStehle** [comment]
Hi, as I mentioned: I did, it was showing me the right number (an 8, followed by 9 other numbers ;)). 

I cannot do it right now because I started it with 8gb, so it is 

1) maxmemory
2) 8589934592

now

**Comment by enricogior** [comment]
@SebastianStehle 
did you run the command after the query failed?
Just checking to make sure the maxmemory value didn't get changed between the service startup and the moment the queries begun to fail.

**Comment by SebastianStehle** [comment]
Yes, I had a look to our log files and recognized that there are hundreds of commands failing. Then I had a look to the redis server.

The task manager says 500mb and the info log tells me:

# Memory

used_memory:3998397176
used_memory_human:3.72G
used_memory_rss:3998396304
used_memory_peak:4825373848
used_memory_peak_human:4.49G
used_memory_lua:442368
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

As mentioned, the config says:
1) maxmemory
2) 8589934592
![untitled](https://cloud.githubusercontent.com/assets/1236435/11836747/f9e39688-a3dc-11e5-9f75-a70dc5b8fdb5.png)

Btw: The other redis process is the sentinel

**Comment by enricogior** [comment]
@SebastianStehle 
I'm currently filling up a test server to see if I can reproduce the problem.
Meanwhile, have you tried from redis-cli to set a key to verify if it fails? (to make sure the error is caused by the server and not by the client).

**Comment by SebastianStehle** [comment]
Not yet, sorry, I need the server for production and at the moment it is working. We had the issue in combination with signalr. The most logs occurred with the following message:

OOM command not allowed when used memory > 'maxmemory'

**Comment by enricogior** [comment]
@SebastianStehle 
I tried to repro the issue setting `maxmemory 8gb` and then filling up the server with small queries, it passed the 5GB value and kept accepting queries (I wanted to make sure that there isn't a major bug when setting the maxmemory limit).
I also tried different values for maxmemory to make sure it always reaches the limit without errors before the limit kicks in.
Therefore I exclude that there is an obvious bug there.

The fact the task manager or process explorer show a lower memory working set is not an issue.
What you might want to check is the "peak working set" that should show the max amount of memory used by the process. The working set is not really significant because of the way Redis allocated the heap memory directly from the system paging file.
You can see the behavior filling the server up to a certain amount (let's say 1GB of working set) and then issue a BGREWRITEOAF command to persist the data to the disk, a child process will show up that also has 1GB of working set memory (but it's actually not using 1GB of physical RAM since it's just virtual address space pointing to the system paging file) and after the child process terminates, the main process working set memory will drop to a lower lever. 

One thing I'm not sure I understand correctly is that you first mentioned "so we defined a maxmemory of 4gb" that would be consistent with getting the memory error since `used_memory_human:4.26G`, but later you wrote "My full config... maxmemory 8gb".
So if the error was occurring with `maxmemory 4gb` and `used_memory_human:4.26G` that is OK.
If the error was occurring with `maxmemory 8gb` and `used_memory_human:4.26G` that is not OK.

**Comment by SebastianStehle** [comment]
Thank you for your fast response. My initial configuration was 4gb and I was confused why I hit the memory limit, because the tasks manager told me that the redis-server only consumes about 500 or so. 

My understanding is that I should not have a look to the task manager in this scenario and that the results from the "info" command are correct, right? So everything is fine for me and it is only a misunderstanding from my side. Would be really cool, if this behavior will be documented.

**Comment by enricogior** [comment]
@SebastianStehle 
yes that's right.
I'll update the wiki and the info in the config file samples to make sure the behavior is documented.
Thank you for bring up the issue.

**Comment by enricogior** [comment]
The [wiki page](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration-For-Redis-3.0) has been updated and the same info has also been added in the sample configuration files.

**Comment by marchenko1985** [comment]
Cross posting here https://github.com/antirez/redis/issues/2136#issuecomment-292530919 hope that helps, just not sure may it be an issue of windows port or original one but sympomps same
