### ISSUE TITLE
2.8.2400 - Windows Server 2008 R2 -SignalR SocketFailure on EVAL

### ISSUE THREAD

**Issue by BoasE** [microsoftarchive/redis#421]
After we upgrdraded to 2.8.2400 our redis server become more stable.

But after running one day. I saw very often this signal R / Redis Error 

On the first day this was about every 5 hours. Now after one day it began to happen more often and often .till we had it every 3 minutes. Then I just restarted the redis server and now about every 30 minutes one time.

```
 StackExchange.Redis.RedisConnectionException: SocketFailure on EVAL
  at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
  at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)

```

any advice?

**Comment by enricogior** [comment]
Hi @Gentlehag 
what version of StackExchange are you using?

**Comment by BoasE** [comment]
strange. we have **ServiceStack.Redis** but the callstack clear says "StackExchange.Redis" Many an SignalR internal ?
I Assume stackexchange comes from Microsoft.aspnet.signalR.Redis. ill investigate this further. All SignalR Packes are most curretn stables

btw the problem is always resolved when only restarten the redis server. and then disappears for hours

**Comment by enricogior** [comment]
@Gentlehag 
it may be a server issue, but it's not 100% sure that is a server issue.
When the service is restarted, that will also cause a client connection reset, so the fact that restarting the service solves the problem is not an indication that is a server-side problem.
One way to check if is a server-side problem is to use a stand alone client like redis-cli.exe.
If redis-cli.exe connects without problems, it's an indication that the service is still working as expected.

**Comment by BoasE** [comment]
this problem only occurs some times and recovers from alone so I can't do much tests here :-/

When I'm more clear about the redis 3.0 problem (in the other thread) i'll move to this again. In 3.0 I never saw this issue ("only" the total hang after some hours")

**Comment by BoasE** [comment]
now i hade the issue that one server only hat there errors. this is a strong indicator for me that the problem is related to the client not to the redis server. so I can close this issue Many thanks for your very helpfull explenations which led me to the right things.
