### ISSUE TITLE
To confirm the licence when installing the msi package

### ISSUE THREAD

**Issue by SS1102** [microsoftarchive/redis#468]
We have installed the latest release of Redis(Redis-x64-2.8.2400.msi), we need to understand the licencing for this.

When I install the msi package there is no file named: licence.txt generated in C:/Program files/Redis which is why I am a bit confused.

Is https://github.com/MSOpenTech/redis/blob/2.8/license.txt the licence for this msi package? If yes, the very first line is '**Copyright (c) 2006-2015, Salvatore Sanfilippo**', will this be valid as it is already mid-2016?

**Comment by enricogior** [comment]
Hi @SS1102 
the last release of the 2.8 branch made by Salvatore Sanfilippo was in 2015, therefore it still stands. On the Windows side we don't change the Salvatore Sanfilippo license even if our lates 2.8.2400 release was made in 2016.

If you are looking for the license shown during the MSI setup, here it is:

Copyright © 2006-2015, Salvatore Sanfilippo
Modifications Copyright © Microsoft Open Technologies, Inc. 
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 
- Neither the name of Redis nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Hopefully that answer your question.
