### ISSUE TITLE
The instruction at 0x3f23f484 referenced memory 0xffffffff. The memory could not be written.

### ISSUE THREAD

**Issue by nathanpalmer** [microsoftarchive/redis#53]
I just downloaded the latest release which was labeled as 2.6.8-pre2 and included a dump from our 2.4 version. The only thing I did was double click on the redis-server to start it up. It seemed to sit there for a minute then hard crashed with this message. The entire virtual machine stopped working after this I had to hard shut down.

![screen shot 2013-07-31 at 1 20 49 pm](https://f.cloud.github.com/assets/125599/888087/f4786880-fa07-11e2-9ab9-78e08cd4c932.png)

**Comment by clca** [comment]
I'll have to take a look and see if I can repro the( problem. Have you tried using the 26 branch or, even better, to install Redis using [NuGet](http://www.nuget.org/packages/Redis-64/)?

**Comment by nathanpalmer** [comment]
Is the Nuget version different than the release here on GitHub? Same question for the branch.

**Comment by clca** [comment]
No the NuGet version is based on the 2.6 branch (that is based on 2.6.12 version available on Linux). We compile the code, sign the binaries and upload the package on the NuGet site, so it is basically the official release for the code that is here on GitHub.
In general I recommend using the latest version (2.6 branch) because it is the branch that went under some extensive testing. Now we are about to release a refresh so the Windows codebase is in sync with the 2.6.14 version on Linux.
I'm also working on adding Redis to WebPI so it will be even easier to install it for all developers that don't need/want to have to deal with the source code.

**Comment by nathanpalmer** [comment]
I'm not worried about distribution or installation at the moment. The version I'm running in the Win2.6.8 zip downloaded from the releases tab here on GitHub. I'm assuming that is also from the 2.6 branch.

**Comment by clca** [comment]
Hi Nathan, can you send me the link from where you downloaded the binaries (they seem to be out of sync)?. I checked on my machine and the binaries from https://github.com/MSOpenTech/redis/tree/2.6/bin/release work fine on my Win8 machine, let me know if they don't work for you and I'll investigate.

**Comment by clca** [comment]
HI Nathan,

Closing this issue, please reopen if you still see the issue and I'll investigate further.
