### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by matthiasg** [microsoftarchive/redis#70]
is there any ongoing commitment from MS to also eventually support 2.8 and beyond ? is development to for 2.8 happening offline again ?

open source is obviously always fickle and development might stop at any time, but regular small commits (without months of gaps) help build up trust...

**Comment by remkoboschker** [comment]
+1

**Comment by mohdmasd** [comment]
I don't know but there're tags labeled with 2.8.x in the repo. Don't know why they don't communicate anything or push their code.

**Comment by sinni800** [comment]
+1

I wonder how much was changed between a given 2.6 and this repo's representation of it. Maybe the changes can be applied to 2.8...

**Comment by williamwsmith** [comment]
+1

Lack of activity concerns me.

**Comment by FlagSystemes** [comment]
+1

**Comment by yarseyah** [comment]
+1

**Comment by clca** [comment]
Sorry for the lack of communication. You haven't seen a lot of activity on the public repo because we are working on fixing some issues we found with the current code. There are some corner cases where it seems we are hitting a race condition so we have been reviewing the code and working on a better solution that will make the code more robust. 
We are making great progress (I can see the end of the tunnel :) )  so you will see us resuming our standard process of using the public repo as our working repo at the beginning of Jan. 
From the commitment to the project point of view: **we are fully committed to continue updating and improving Redis on Windows**, as soon as we have the new code done we will start immediately on the 2.8 codebase in order to get a Windows version out as quickly as possible.

**Comment by clca** [comment]
BTW: we are currently working out of the 2_6_14_Rebase branch. This will become the new codebase we are going to use moving forward. We have made some significant improvements to our code so it will allow us to move faster and get a par with Linux (2.8) very soon.

**Comment by remkoboschker** [comment]
Thank you for the update

**Comment by factormystic** [comment]
Thanks for the comment @clca but how about actually pushing the in progress code?

**Comment by sinni800** [comment]
If you would just release the 2.8 branch in it's incomplete state, people could send you pull requests to help you out in finishing it... And issues. You know, work together and stuff. Collaborate.

**Comment by clca** [comment]
the in progress code is available under the 2_6_14_Rebase branch, this is our current working branch. We haven't started with 2.8 yet. We want to close with the 2.6 codebase and then move to 2.8. In general we always use the public repo, in few cases we decided to go offline for a while in order to avoid potential randomization caused by us testing various options and so on. In general contributions/comments/suggestions and anything that can help us to make Redis on Windows better are all welcome.
After the significant refactoring of the code is completed you will see more progress and we should be able to get the 2.8 codebase up on the side fairly soon.

**Comment by tw-bert** [comment]
Thanks for the update.
+1 for 2.8, all in due time ofcourse.

**Comment by glikoz** [comment]
There is 2.6.17 in releases folder. Is it final work for 2.6.x? If so could you upload compiled runnable version of it? I installed 2.6.12 from here 3-4 months ago but now I could not find it also.. 
Thanks.

**Comment by marcottedan** [comment]
Is https://github.com/MSOpenTech/redis/releases/tag/2.8.4 a valid Tag for Windows? You released it 3 days ago but 7 days ago you said that you want to close 2.6 before moving to 2.8.

**Comment by jepickett** [comment]
Hi Daniel,

This looks like the antirez/linux version of 2.8. It does not contain any of the changes we have been making to support Windows.

We are currently finalizing 2.6.14. In this  release there will be major improvements to both the networking layer and the background saving mechanisms. I don’t have an official timeline for this, but it should be available “real soon now”. Once this is available, we will be moving on to a newer version of Redis. 2.8 is at the top of our priority list.

Thanks,
Jonathan

**Comment by m-manu** [comment]
It would help if you can share actual date of realize for '2.8.4 for Windows'.

**Comment by clca** [comment]
We are going to push the code in the repo either today or tomorrow. We have still a couple of unit tests that are failing but we are pretty close. We will officially release the 2.8 codebase as soon as we have completed our test pass.

**Comment by factormystic** [comment]
@clca that's good news. But don't let failing tests stop you from always pushing the code. If you're not ready for release, simply don't tag a release on the branch and perhaps add a warning to the readme that the latest branch commits are in-progress. This is a very common practice on github. Nobody can tell if any work is being done when you don't push the commits, so even test-breaking commits are preferable to no commits.

**Comment by matthiasg** [comment]
Any news ? ...

**Comment by clca** [comment]
Yes, the code will be pushed later today. There is still an open issue with BLPOP that we are still working on but the code should be stable enough for some initial testing.

**Comment by jepickett** [comment]
The code has been pushed up to the 2.8.4_msopen branch. This is alpha quality at this point. Unit tests involving BLPOP(unit/protocol.tcl, unit/type/list.tcl, and unit/scripting.tcl) will crash Redis. There are a couple other unit test warnings as well.

**Comment by matthiasg** [comment]
Thanks for the push !

Sadly when compiling using `msbuild /p:Configuration=Release` (or Debug for that matter) it compiles fine (76 warnings,0 errors), but upon starting `redis-server.exe` i get this:

```
Problem mapping heap.            
Error ocurred initializing Redis.
```

This is on Windows 8.1 x64 (32GB RAM,24Cores,NUMA).

**Comment by jepickett** [comment]
Thanks for reporting the problem.

Have you tried this on another machine? The new quasi-fork implementation for background AOF and RDB operations uses a memory mapped file that is the size of physical RAM - 3GB. You will need sufficient free disk space for that file. I will improve the error reporting so that we can get the error code from the failing API.

**Comment by matthiasg** [comment]
It could be the free disk space .. I am developing on a ssd .. Not sure if it has 29gb free .. Not sure that's a  great requirement though, the customer machines we use with redis have 512gb of RAM with 2x  PCI ssd cards also with 512 GB each ... That would mean we couldn't store basically any data on the PCI drives ... 

Is this going away or meant to stay ? Didn't notice this on UNIX with 2.8 ...

-----Original Message-----

**Comment by jepickett** [comment]
Our goal is to build a reliable version of Redis on Windows with performance comparable to the UNIX version. In order to do this there are compromises we have to make in our implementation. In this case the extra disk usage is an unavoidable tradeoff.

Windows does not have anything that will exactly replicate the behavior of fork(). The background AOF and RDB operations in Redis has been designed around the point-in-time snapshot behavior of fork(). Our previous attempts to deal with this issue have produced undesirable results in Redis: either slow performance or unstable code. We have looked at several fork implementations and decided that implementing our own would give us the ability to precisely tailor our implementation to both honor the design of Redis, and maintain the level of performance that is expected. 

In order to simulate the fork() snapshot behavior, we start with a Section/MemoryMappedFile object that serves as the Redis heap. This object needs to be mapped into both the parent and child processes at the same virtual address so that the list code can access linked nodes identically in each process. Attempts to use the system paging file for this purpose fails when we try to map the object into the child process at the required address. The only solution that allowed shared memory mapping at identical addresses was a separate disk based memory map file. The size of this file (physical memory-3GB) was chosen to maximize the amount of virtual memory available to the Redis heap, while also preventing excessive page swapping of the OS during periods of high physical memory demand. While this is an unfortunate requirement on Windows, our hope is that the improvements we have seen in stability is worth the cost.

**Comment by matthiasg** [comment]
I do understand the design decision and agree with it, but the heap size should be configurable. I only need 2 or 3 GB for session stores and some operations stuff. Consuming 499gb for that, just because Redis happens to run on a 512GB RAM machine is not a good trade off.

-----Original Message-----

**Comment by matthiasg** [comment]
I just tried to start on a larger drive with 51GB free. I still get the same error message. Using procmon I can see redis-server.exe trying to create a RedisQFork_13556.dat with 31 071 404 032 bytes on a drive that has more than 51 000 000 000 bytes free. Still it did not work.

**Comment by jepickett** [comment]
What result code is coming back from the failing CreateFile operation in ProcMon?

**Comment by jepickett** [comment]
I have added a new flag for controlling the size of the heap, and thus the memory mapped file allocated for the heap. I have pushed this change to the 2.8.4_msopen branch. The flag is "--maxheapgb [heap size in GB]". Let me know if this solves your problem.

**Comment by matthiasg** [comment]
pulled the code:

with the new code (no flag) I get the following console output:

```
QForkMasterInit: system error caught. error code=0x000005af, message=QForkMasterInit:VirtualAllocEx failed.                                        
```

and this output in procmon

```
10:50:02,3630113    redis-server.exe    23036   QueryOpen   E:\opensource\redis\msvs\x64\Release\redis-server.exe   SUCCESS CreationTime: 04.02.2014 07:34:21, LastAccessTime: 04.02.2014 07:34:21, LastWriteTime: 06.02.2014 10:48:48, ChangeTime: 06.02.2014 10:48:48, AllocationSize: 708.608, EndOfFile: 706.048, FileAttributes: A
10:50:02,3630971    redis-server.exe    23036   QuerySecurityFile   E:\opensource\redis\msvs\x64\Release\redis-server.exe   BUFFER OVERFLOW Information: Owner
10:50:02,3631120    redis-server.exe    23036   QuerySecurityFile   E:\opensource\redis\msvs\x64\Release\redis-server.exe   SUCCESS Information: Owner
10:50:02,3660493    redis-server.exe    23036   CreateFile  G:\RedisQFork_23036.dat SUCCESS Desired Access: Generic Read/Write, Delete, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Delete On Close, Attributes: N, ShareMode: None, AllocationSize: 0, OpenResult: Created
10:50:02,3661733    redis-server.exe    23036   CreateFileMapping   G:\RedisQFork_23036.dat FILE LOCKED WITH WRITERS    SyncType: SyncTypeCreateSection, PageProtection: 
10:50:02,3661846    redis-server.exe    23036   QueryStandardInformationFile    G:\RedisQFork_23036.dat SUCCESS AllocationSize: 0, EndOfFile: 0, NumberOfLinks: 1, DeletePending: False, Directory: False
10:50:02,3661970    redis-server.exe    23036   SetEndOfFileInformationFile G:\RedisQFork_23036.dat SUCCESS EndOfFile: 31.071.404.032
10:50:02,7206184    redis-server.exe    23036   CreateFileMapping   G:\RedisQFork_23036.dat SUCCESS SyncType: SyncTypeOther
10:50:02,7234460    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\KernelBase.dll  SUCCESS Name: \Windows\System32\KernelBase.dll
10:50:02,7234707    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\user32.dll  SUCCESS Name: \Windows\System32\user32.dll
10:50:02,7234869    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\imm32.dll   SUCCESS Name: \Windows\System32\imm32.dll
10:50:02,7235011    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\sechost.dll SUCCESS Name: \Windows\System32\sechost.dll
10:50:02,7235155    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\rpcrt4.dll  SUCCESS Name: \Windows\System32\rpcrt4.dll
10:50:02,7235293    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\gdi32.dll   SUCCESS Name: \Windows\System32\gdi32.dll
10:50:02,7235427    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\msctf.dll   SUCCESS Name: \Windows\System32\msctf.dll
10:50:02,7235569    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\advapi32.dll    SUCCESS Name: \Windows\System32\advapi32.dll
10:50:02,7235706    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\ws2_32.dll  SUCCESS Name: \Windows\System32\ws2_32.dll
10:50:02,7235886    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\kernel32.dll    SUCCESS Name: \Windows\System32\kernel32.dll
10:50:02,7236045    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\nsi.dll SUCCESS Name: \Windows\System32\nsi.dll
10:50:02,7236190    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\msvcrt.dll  SUCCESS Name: \Windows\System32\msvcrt.dll
10:50:02,7236335    redis-server.exe    23036   QueryNameInformationFile    C:\Windows\System32\ntdll.dll   SUCCESS Name: \Windows\System32\ntdll.dll
10:50:02,7237041    redis-server.exe    23036   CloseFile   G:\ SUCCESS 
10:50:02,7238606    redis-server.exe    23036   CloseFile   G:\RedisQFork_23036.dat SUCCESS 

```

Using the --maxheapgb option with something small like `4` it start without issues.
Using the --maxheapgb option with e.g `15` it fails too, when i have 16,7GB free so it seems maxheapgb really means reserve from heap .. and getting too close to free mem fails the server ?

**Comment by jepickett** [comment]
FYI, I just pushed a change that removes the maxheapgb flag and instead utilizes the existing maxmemory flag. I have also made the the qfork code recognize the maxmemory flag if present in a .conf file. The MM file size will track the maxmemory flag, rounded up by the heap block size of 64MB.The minimum MM file will be 2x the allocation granularity used for the heap blocks (128MB). Recent changes also allow Redis to start on much smaller machines (i.e., Azure XS VM). I have pushed this change in both the 2.6.14 and 2.8.4 branches. The binaries have been updated. 

Sharing memory between processes reserves a portion of the system paging file for the shared memory segment. Error code 0x5af indicates that the system paging file is full or too heavily fragmented to allocate a contiguous block from.  If your paging file is configured with low upper size limit, or is being used heavily by other processes you may receive this error. By default the paging file should expand on demand to about 3x physical memory. You can specify a larger paging file in the system control panel in the Virtual Memory setting in the Advanced tab.

**Comment by jepickett** [comment]
2.8.4 has been released. Signed binaries are available from NuGet and Chocolatey. See the release notes and redis.windows.conf file for the usage semantics for the maxheap flag.

**Comment by tw-bert** [comment]
Thanks for the release! Much appreciated.
