### ISSUE TITLE
APIBridge removal

### ISSUE THREAD

**Issue by hrishi18pathak** [microsoftarchive/redis#88]
The implementation of Win32_FDApi.cpp has changed to use the dllfunctor For e.g: dllfunctor_stdcall<BOOL, SOCKET, LPWSAOVERLAPPED, LPDWORD, BOOL, LPDWORD>("ws2_32.dll", "WSAGetOverlappedResult"). Initially this used to be invoked from the APIBridge which used to statically link ws2_32.lib. Was there any reason for this change?

**Comment by jepickett** [comment]
In Win32_FDAPI I have implemented a UNIX file descriptor layer (socket+low level io). This allows the majority of Redis networking/io code to compile without change. Unfortunately the function names and prototypes used by UNIX conflict with the names specified by ws2_32.lib. In order to get around this I can not directly link to this import library.  To keep things separate I introduced APIBridge.dll. This allowed me to call into WinSock without all the linker conflicts. Unfortunately introducing a DLL into the project also meant that we had to link to the DLL version of the CRT. This introduces a dependency on the CRT redistributable. This also means that we need a setup. After some complaints about this we decided to change the aliasing implementation to LoadLibrary/GetProcAddress. With this change I could go back to the static version of the CRT, and we are once again xcopy deployable.
